// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJbfvxQLD4aii5S5eFq7JOFZpNsVQmt8',
    appId: '1:335030332386:web:cfbfe0ce2456e1134f67bb',
    messagingSenderId: '335030332386',
    projectId: 'switch-it-5dfca',
    authDomain: 'switch-it-5dfca.firebaseapp.com',
    storageBucket: 'switch-it-5dfca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvlGEaTQGErXcwr2s1qaVT9dODYic8QI',
    appId: '1:335030332386:android:d7d044616e28e4a34f67bb',
    messagingSenderId: '335030332386',
    projectId: 'switch-it-5dfca',
    storageBucket: 'switch-it-5dfca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxdxumJK4XVYWCBlGAOGPfs0xIBIaD8Y',
    appId: '1:335030332386:ios:634dd03d500521ec4f67bb',
    messagingSenderId: '335030332386',
    projectId: 'switch-it-5dfca',
    storageBucket: 'switch-it-5dfca.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUxdxumJK4XVYWCBlGAOGPfs0xIBIaD8Y',
    appId: '1:335030332386:ios:ef43990499851b234f67bb',
    messagingSenderId: '335030332386',
    projectId: 'switch-it-5dfca',
    storageBucket: 'switch-it-5dfca.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
